[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["curl -fsSL https://bun.sh/install | bash", "npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = []

[start]
cmd = "bun run src/index.ts"